## Basic Configuration
baseurl = "https://thinkloveshare.github.io/"
title = "Think\nLove\nShare"
pluralizelisttitles = "false"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
googleAnalytics = "UA-128985075-1"
enableRobotsTXT = true

## Site Settings
[params]
    author = "Laluka"
    title = "ThinkLoveShare"
    description = "Infosec, Coding, Thoughts & Feels"
    authorimage = "/img/laluka.png"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    highlightjsstyle = "github"

## Social Accounts
[params.social]
    github = "TheLaluka"
    linkedin = "louka-jacques-chevallier-6b2460125"
    twitter = "thelaluka"
    email = "loukajc@gmail.com"
    rootme = "Laluka"
    aperikube = "aperikube"

[Languages]
  [Languages.en]
    ## Main Menu
    [[Languages.en.menu.main]]
        name = "Coding"
        weight = 1
        identifier = "coding"
        url = "/en/coding/"
    [[Languages.en.menu.main]]
        name = "Hacking"
        weight = 2
        identifier = "hacking"
        url = "/en/hacking/"
    [[Languages.en.menu.main]]
        name = "Write-Ups"
        identifier = "writeups"
        weight = 3
        url = "/en/writeups/"
    [[Languages.en.menu.main]]
        name = "The rest"
        identifier = "the_rest"
        weight = 4
        url = "/en/the_rest/"
    [[Languages.en.menu.main]]
        name = "About"
        identifier = "about"
        weight = 5
        url = "/en/about/"

  [Languages.fr]
    ## Main Menu
    [[Languages.fr.menu.main]]
        name = "Coding"
        weight = 1
        identifier = "coding"
        url = "/fr/coding/"
    [[Languages.fr.menu.main]]
        name = "Hacking"
        weight = 2
        identifier = "hacking"
        url = "/fr/hacking/"
    [[Languages.fr.menu.main]]
        name = "Write-Ups"
        identifier = "writeups"
        weight = 3
        url = "/fr/writeups/"
    [[Languages.fr.menu.main]]
        name = "Le reste"
        identifier = "the_rest"
        weight = 4
        url = "/fr/the_rest/"
    [[Languages.fr.menu.main]]
        name = "À propos"
        identifier = "apropos"
        weight = 5
        url = "/fr/apropos/"
